#!/usr/bin/env bash

function prepend_dir() {
    local var="$1"
    local dir="$2"

    if [ -d "$dir" ]; then
        eval "export $var=\"\$dir\${$var:+:\$$var}\""
    fi
}

function append_dir() {
    local var="$1"
    local dir="$2"

    if [ -d "$dir" ]; then
        eval "export $var=\"\${$var:+\$$var:}\$dir\""
    fi
}

if [ "$SNAP_ARCH" == "amd64" ]; then
    ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" == "armhf" ]; then
    ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" == "arm64" ]; then
    ARCH="aarch64-linux-gnu"
elif [ "$SNAP_ARCH" == "ppc64el" ]; then
    ARCH="powerpc64le-linux-gnu"
else
    ARCH="$SNAP_ARCH-linux-gnu"
fi

export LC_ALL=C.UTF-8

export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/$ARCH/dri
export LIBVA_DRIVERS_PATH=$SNAP/usr/lib/$ARCH/dri

# EGL vendor files on glvnd enabled systems
[ -d /var/lib/snapd/lib/glvnd/egl_vendor.d ] \
    && prepend_dir __EGL_VENDOR_LIBRARY_DIRS /var/lib/snapd/lib/glvnd/egl_vendor.d

# EGL vendor files
append_dir __EGL_VENDOR_LIBRARY_DIRS $SNAP/etc/glvnd/egl_vendor.d
append_dir __EGL_VENDOR_LIBRARY_DIRS $SNAP/usr/share/glvnd/egl_vendor.d

exec "$@"
